'use strict';
const puppeteer = require('puppeteer'); const chromium = require('@sparticuz/chromium'); const { v4: uuid } = require('uuid'); const EventEmitter = require('events');
const MAX_ACTIVE = Math.max(1, Math.min(parseInt(process.env.MAX_ACTIVE, 10) || 3, 20)); const SCREENSHOT_INTERVAL = Math.max(400, Math.min(parseInt(process.env.SCREENSHOT_INTERVAL, 10) || 800, 5000));
class VirtualDevice extends EventEmitter {
  constructor(o = {}) { super(); Object.assign(this, { id: o.id || uuid(), name: o.name || `Device-${uuid().slice(0, 6)}`, brand: o.brand || 'Samsung', model: o.model || 'Galaxy A54 5G', android: o.android || '13', width: o.width || 393, height: o.height || 851, ram: o.ram || '6GB', cpu: o.cpu || 'Exynos 1380', group: o.group || 'Default', notes: o.notes || '', browser: null, page: null, status: 'stopped', currentUrl: 'about:blank', battery: 85 + Math.floor(Math.random() * 15), signal: 3 + Math.floor(Math.random() * 2), startedAt: null, uptime: 0, screenTimer: null, uptimeTimer: null, error: null }); this.userAgent = o.userAgent || this._buildUA(); }
  async start() { if (this.browser) return; this.status = 'starting'; try { this.browser = await puppeteer.launch({ headless: 'new', executablePath: process.env.PUPPETEER_EXEC || await chromium.executablePath(), args: [...chromium.args, '--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage', '--disable-gpu', '--disable-extensions', '--single-process', `--window-size=${this.width},${this.height}`], defaultViewport: { width: this.width, height: this.height, deviceScaleFactor: this.width >= 393 ? 3 : 2.75, isMobile: true, hasTouch: true } }); this.page = await this.browser.newPage(); await this.page.setUserAgent(this.userAgent); await this.page.setRequestInterception(true); this.page.on('request', r => ['media', 'font'].includes(r.resourceType()) ? r.abort() : r.continue()); await this.page.goto('https://example.com', { waitUntil: 'domcontentloaded', timeout: 20000 }).catch(() => {}); this.status = 'running'; this.startedAt = Date.now(); this.error = null; this.screenTimer = setInterval(() => this._sendFrame(), SCREENSHOT_INTERVAL); this.uptimeTimer = setInterval(() => { this.uptime++; this.battery = Math.max(10, this.battery - 0.001); }, 1000); if (global.io) global.io.emit('device:started', this.toJSON()); } catch (e) { this.error = e.message; await this.stop(); this.status = 'error'; throw e; } }
  async stop() { clearInterval(this.screenTimer); clearInterval(this.uptimeTimer); this.screenTimer = null; this.uptimeTimer = null; if (this.browser) await this.browser.close().catch(() => {}); this.browser = null; this.page = null; this.status = 'stopped'; if (global.io) global.io.emit('device:stopped', { id: this.id }); }
  async goto(url) { let u; try { u = new URL(String(url).startsWith('http') ? String(url) : `https://${String(url)}`); } catch { throw new Error('Invalid URL'); } if (!['http:', 'https:'].includes(u.protocol)) throw new Error('Only http and https URLs are allowed.'); if (!this.page) throw new Error('Device not running'); await this.page.goto(u.toString(), { waitUntil: 'domcontentloaded', timeout: 30000 }); this.currentUrl = this.page.url(); return this.currentUrl; }
  async back() { await this.page?.goBack({ timeout: 5000 }).catch(() => {}); } async forward() { await this.page?.goForward({ timeout: 5000 }).catch(() => {}); } async reload() { await this.page?.reload({ timeout: 10000 }).catch(() => {}); }
  async tap(x, y) { if (this.page) await this.page.touchscreen.tap(Number(x), Number(y)).catch(() => this.page.mouse.click(Number(x), Number(y))); } async doubleTap(x, y) { await this.tap(x, y); await this._sleep(100); await this.tap(x, y); } async longPress(x, y, ms = 1000) { if (!this.page) return; await this.page.mouse.move(x, y); await this.page.mouse.down(); await this._sleep(Math.min(Number(ms) || 1000, 10000)); await this.page.mouse.up(); }
  async swipe(x1, y1, x2, y2, ms = 300) { if (!this.page) return; const steps = Math.max(5, Math.floor(Math.min(Number(ms) || 300, 3000) / 16)); await this.page.mouse.move(x1, y1); await this.page.mouse.down(); await this.page.mouse.move(x2, y2, { steps }); await this.page.mouse.up(); } swipeUp() { return this.swipe(this.width / 2, this.height * .75, this.width / 2, this.height * .25); } swipeDown() { return this.swipe(this.width / 2, this.height * .25, this.width / 2, this.height * .75); } swipeLeft() { return this.swipe(this.width * .85, this.height / 2, this.width * .15, this.height / 2); } swipeRight() { return this.swipe(this.width * .15, this.height / 2, this.width * .85, this.height / 2); }
  async type(t) { if (this.page) await this.page.keyboard.type(String(t || '').slice(0, 4000), { delay: 40 }); } async pressKey(k) { if (this.page) await this.page.keyboard.press(String(k || '')); } async clearInput() { await this.pressKey('Control+a'); await this.pressKey('Backspace'); } async scrollDown(px = 400) { await this.page?.evaluate(y => window.scrollBy(0, y), Number(px) || 400); } async scrollUp(px = 400) { await this.page?.evaluate(y => window.scrollBy(0, -y), Number(px) || 400); } async scrollToTop() { await this.page?.evaluate(() => window.scrollTo(0, 0)); } async scrollToBottom() { await this.page?.evaluate(() => window.scrollTo(0, document.body.scrollHeight)); }
  async eval(code) { if (process.env.ENABLE_BROWSER_EVAL !== 'true') throw new Error('Browser evaluation is disabled by default; enable only for authorized QA.'); return this.page?.evaluate(String(code || '').slice(0, 20000)); } async screenshot() { return this.page?.screenshot({ encoding: 'base64', type: 'jpeg', quality: 60 }).catch(() => null); } async _sendFrame() { if (!this.page || this.status === 'stopped' || !global.io) return; const frame = await this.screenshot(); if (frame) global.io.volatile.emit(`device:frame:${this.id}`, { id: this.id, frame, url: this.page.url(), ts: Date.now() }); }
  _sleep(ms) { return new Promise(r => setTimeout(r, ms)); } _buildUA() { return `Mozilla/5.0 (Linux; Android ${this.android}; ${this.model}) AppleWebKit/537.36 Chrome/120 Mobile Safari/537.36`; } toJSON() { return { id: this.id, name: this.name, brand: this.brand, model: this.model, android: this.android, width: this.width, height: this.height, ram: this.ram, cpu: this.cpu, group: this.group, notes: this.notes, status: this.status, currentUrl: this.page?.url() || this.currentUrl, battery: Math.round(this.battery), signal: this.signal, uptime: this.uptime, startedAt: this.startedAt, error: this.error }; }
}
class DevicePool extends EventEmitter {
  constructor() { super(); this.devices = new Map(); this.audit = []; this.maxActive = MAX_ACTIVE; this.screenshotInterval = SCREENSHOT_INTERVAL; } record(event, detail = {}) { this.audit.unshift({ at: new Date().toISOString(), event, ...detail }); this.audit = this.audit.slice(0, 200); } getAudit() { return this.audit; }
  async add(o = {}) { const d = new VirtualDevice(o); this.devices.set(d.id, d); this.record('device.created', { id: d.id, name: d.name }); if (this._activeCount() < MAX_ACTIVE) d.start().catch(e => { this.record('device.error', { id: d.id, error: e.message }); if (global.io) global.io.emit('device:error', { id: d.id, error: e.message }); }); else d.status = 'queued'; if (global.io) global.io.emit('device:added', d.toJSON()); return d; }
  async addMany(list) { const out = []; for (const o of list.slice(0, 20)) { out.push(await this.add(o)); await new Promise(r => setTimeout(r, 250)); } return out; } async remove(id) { const d = this.devices.get(id); if (!d) return; await d.stop(); this.devices.delete(id); this.record('device.removed', { id }); this._startNext(); } async removeAll() { await Promise.all([...this.devices.keys()].map(id => this.remove(id))); } get(id) { return this.devices.get(id); } getAll() { return [...this.devices.values()]; } getAllJSON() { return this.getAll().map(d => d.toJSON()); }
  async startAll() { for (const d of this.devices.values()) if ((d.status === 'stopped' || d.status === 'queued') && this._activeCount() < MAX_ACTIVE) await d.start().catch(() => {}); } async stopAll() { await Promise.all(this.getAll().map(d => d.stop().catch(() => {}))); }
  async action(id, action, p = {}) { const d = this.devices.get(id); if (!d) throw new Error('Device not found'); if (d.status === 'stopped' || d.status === 'queued') await d.start(); this.record('device.action', { id, action }); const m = { tap: () => d.tap(p.x, p.y), double_tap: () => d.doubleTap(p.x, p.y), long_press: () => d.longPress(p.x, p.y, p.ms), swipe: () => d.swipe(p.x1, p.y1, p.x2, p.y2, p.ms), swipe_up: () => d.swipeUp(), swipe_down: () => d.swipeDown(), swipe_left: () => d.swipeLeft(), swipe_right: () => d.swipeRight(), type: () => d.type(p.text), key: () => d.pressKey(p.key), clear: () => d.clearInput(), scroll_down: () => d.scrollDown(p.px), scroll_up: () => d.scrollUp(p.px), scroll_top: () => d.scrollToTop(), scroll_bottom: () => d.scrollToBottom(), back: () => d.back(), forward: () => d.forward(), reload: () => d.reload(), goto: () => d.goto(p.url), screenshot: () => d.screenshot(), eval: () => d.eval(p.code), get_html: () => d.page?.content(), get_title: () => d.page?.title(), get_url: () => d.page?.url() }; if (!m[action]) throw new Error(`Unknown action: ${action}`); return m[action](); }
  batch(ids, action, params = {}) { return Promise.allSettled(ids.slice(0, 50).map(id => this.action(id, action, params))); } _activeCount() { return this.getAll().filter(d => d.browser).length; } _startNext() { const d = this.getAll().find(x => x.status === 'queued'); if (d && this._activeCount() < MAX_ACTIVE) d.start().catch(() => {}); } getStats() { const a = this.getAll(); return { total: a.length, running: a.filter(d => ['running', 'busy'].includes(d.status)).length, stopped: a.filter(d => d.status === 'stopped').length, queued: a.filter(d => d.status === 'queued').length, error: a.filter(d => d.status === 'error').length, maxActive: MAX_ACTIVE }; }
}
module.exports = { DevicePool, VirtualDevice };
